### ISSUE TITLE
Spams error when ProtocolLib is Installed

### ISSUE THREAD

**Issue by RORY112345** [Archy-X/AureliumSkills#103]
### Server software and version

Spigot 1.19

### Expected behavior

Doesn't spam errors at console

### Actual behavior

When ProtocolLib is installed, It spams " ```
Task #64 for AureliumSkills vBeta 1.3.6 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.archyx.aureliumskills.support.ProtocolLibSupport.sendNewActionBar(ProtocolLibSupport.java:23) ~[?:?]
        at com.archyx.aureliumskills.ui.ActionBar.sendActionBar(ActionBar.java:283) ~[?:?]
        at com.archyx.aureliumskills.ui.ActionBar.lambda$startUpdateActionBar$0(ActionBar.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1010) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>stop
[07:51:40] [Server thread/WARN]: [AureliumSkills] Task #64 for AureliumSkills vBeta 1.3.6 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.archyx.aureliumskills.support.ProtocolLibSupport.sendNewActionBar(ProtocolLibSupport.java:23) ~[?:?]
        at com.archyx.aureliumskills.ui.ActionBar.sendActionBar(ActionBar.java:283) ~[?:?]
        at com.archyx.aureliumskills.ui.ActionBar.lambda$startUpdateActionBar$0(ActionBar.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1010) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3508-Spigot-fa893f0-50ef122]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```"

### How to reproduce

1. Download ProtocolLib
2. Download AureliumSkills
3. Start Server
4. Error there.

### Additional information

_No response_

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Are you using the latest dev build version of ProtocolLib found https://ci.dmulloy2.net/job/ProtocolLib/ ?
The version on Spigot doesn't support 1.19 yet.

**Comment by RORY112345** [comment]
> Are you using the latest dev build version of ProtocolLib found https://ci.dmulloy2.net/job/ProtocolLib/ ? The version on Spigot doesn't support 1.19 yet.

Oh, I used one on the spigot website. Thanks!
