### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by Regomy** [Archy-X/AureliumSkills#121]
### Server software and version

Paper 1,12,2

### Expected behavior

[05:16:41 WARN]: [AureliumSkills] Error parsing loot in file loot/fishing.yml at path pools.epic.loot.9, see below for error:
[05:16:41 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.potion.PotionType.TURTLE_MASTER
[05:16:41 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:240)
[05:16:41 WARN]:        at org.bukkit.potion.PotionType.valueOf(PotionType.java:7)
[05:16:41 WARN]:        at com.archyx.lootmanager.loot.parser.ItemLootParser.parseItem(ItemLootParser.java:143)
[05:16:41 WARN]:        at com.archyx.lootmanager.loot.parser.ItemLootParser.parse(ItemLootParser.java:47)
[05:16:41 WARN]:        at com.archyx.lootmanager.loot.LootLoader.loadLootTable(LootLoader.java:65)
[05:16:41 WARN]:        at com.archyx.aureliumskills.loot.LootTableManager.loadLootTables(LootTableManager.java:87)
[05:16:41 WARN]:        at com.archyx.aureliumskills.loot.LootTableManager.<init>(LootTableManager.java:32)
[05:16:41 WARN]:        at com.archyx.aureliumskills.AureliumSkills.onEnable(AureliumSkills.java:326)
[05:16:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:16:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[05:16:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:16:41 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[05:16:41 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[05:16:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[05:16:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[05:16:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[05:16:41 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[05:16:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[05:16:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

### Actual behavior

fsdf

### How to reproduce

sdfsdfs

### Additional information

sdfsdf

### Agreements

- [ ] I am running the latest version of Aurelium Skills
- [ ] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [ ] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Minecraft 1.12 is no longer supported, but you could easily remove that loot with turtle master in the loot/fishing.yml file
