### ISSUE TITLE
Error occurred while enabling AureliumSkills vBeta 1.3.12 (Is it up to date?)

### ISSUE THREAD

**Issue by Aliorpse** [Archy-X/AureliumSkills#155]
### Server software and version

Paper 1.19.2

### Expected behavior

the plugin loads normally

### Actual behavior

didnt load normally and
[16:13:47] [Server thread/ERROR]: Error occurred while enabling AureliumSkills vBeta 1.3.12 (Is it up to date?)
java.lang.NoSuchFieldError: SYSTEM_CHAT
	at com.archyx.aureliumskills.ui.ActionBarCompatHandler.registerSystemChatListener(ActionBarCompatHandler.java:53) ~[AureliumSkills-Beta1.3.12.jar:?]
	at com.archyx.aureliumskills.ui.ActionBarCompatHandler.registerListeners(ActionBarCompatHandler.java:35) ~[AureliumSkills-Beta1.3.12.jar:?]
	at com.archyx.aureliumskills.AureliumSkills.onEnable(AureliumSkills.java:285) ~[AureliumSkills-Beta1.3.12.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-270]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

null

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Your ProtocolLib must be the latest dev build: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Aliorpse** [comment]
ok thanks
