### ISSUE TITLE
Unknown error reported

### ISSUE THREAD

**Issue by RAURORA2** [Archy-X/AureliumSkills#164]
### Server software and version

purpur1.19.2

### Expected behavior

Unknown error reported

### Actual behavior

[12:24:02 警告]: [AureliumSkills] Task #7763675 for AureliumSkills vBeta 1.3.13 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.archyx.aureliumskills.ui.SkillBossBar$1.run(SkillBossBar.java:239) ~[AureliumSkills-Beta1.3.13.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Unknown error reported

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Should be fixed in Beta 1.3.14
