### ISSUE TITLE
[13:16:37 WARN]: Error while updating leaderboards:

### ISSUE THREAD

**Issue by yuankun1** [Archy-X/AureliumSkills#49]
[13:16:37 WARN]: Error while updating leaderboards:
[13:16:37 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 539,908 milliseconds ago. The last packet sent successfully to the server was 539,908 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[13:16:37 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[13:16:37 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[13:16:37 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1198)
[13:16:37 WARN]:        at [A][技能]AureliumSkills-Beta1.2.0.jar//com.archyx.aureliumskills.data.storage.MySqlStorageProvider.updateLeaderboards(MySqlStorageProvider.java:435)
[13:16:37 WARN]:        at [A][技能]AureliumSkills-Beta1.2.0.jar//com.archyx.aureliumskills.AureliumSkills$1.run(AureliumSkills.java:308)
[13:16:37 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:16:37 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:16:37 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:16:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:16:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:16:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:16:37 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 539,908 milliseconds ago. The last packet sent successfully to the server was 539,908 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[13:16:37 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor129.newInstance(Unknown Source)
[13:16:37 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:16:37 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:16:37 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:16:37 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[13:16:37 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[13:16:37 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[13:16:37 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:577)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:632)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:948)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:894)
[13:16:37 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)
[13:16:37 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1166)
[13:16:37 WARN]:        ... 8 more
[13:16:37 WARN]: Caused by: java.net.SocketException: 你的主机中的软件中止了一个已建立的连接。
[13:16:37 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[13:16:37 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[13:16:37 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[13:16:37 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
[13:16:37 WARN]:        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
[13:16:37 WARN]:        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
[13:16:37 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:568)
[13:16:37 WARN]:        ... 13 more

**Comment by Archy-X** [comment]
Check to make sure your database connection is stable, it seems to have disconnected for some reason (even though autoreconnect is enabled)

**Comment by yuankun1** [comment]
> 检查以确保您的数据库连接是稳定的，它似乎由于某种原因而断开连接(即使启用了自动重新连接)。



I make sure the database is stable
Aurelium Skills and CMI Mysql The two conflict with each other

**Comment by yuankun1** [comment]
> > Check to make sure your database connection is stable, it seems to have disconnected for some reason (even though autoreconnect is enabled)。
> 
> I make sure the database is stable
> Aurelium Skills and CMI Mysql The two conflict with each other

**Comment by Archy-X** [comment]
Make sure you are using separate databases for each plugin

**Comment by yuankun1** [comment]
> Make sure you are using separate databases for each plugin

I have determined that each plug-in is a separate database

**Comment by yuankun1** [comment]
> Make sure you are using separate databases for each plugin

This is the configuration file of CMI database   
autoReconnect: true

storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: Mysql
mysql:
  # Requires Mysql.
  username: xxxx
  password: 'xxxx'
  hostname: localhost:3306
  database: xxxx
  # Valid characters are a-z 0-9 and _
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 30
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false

**Comment by Archy-X** [comment]
Unable to reproduce this issue, reopen if you have additional info
