### ISSUE TITLE
Mysql bug

### ISSUE THREAD

**Issue by enzomtpYT** [Archy-X/AureliumSkills#70]
### Server software and version

Paper 1.17.1

### Expected behavior

Sql connection should work

### Actual behavior

Plugin is unloading of my server

Heres logs :

```
ERROR
17:48:05

Error occurred while enabling AureliumSkills vBeta 1.2.5 (Is it up to date?)

Console
17:48:05

java.lang.NullPointerException: Cannot invoke "java.sql.Connection.getMetaData()" because "this.connection" is null
at com.archyx.aureliumskills.data.storage.MySqlStorageProvider.localeColumnExists(MySqlStorageProvider.java:401) ~[AureliumSkills-Beta1.2.5.jar:?]
at com.archyx.aureliumskills.AureliumSkills.onEnable(AureliumSkills.java:289) ~[AureliumSkills-Beta1.2.5.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-378]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-378]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-378]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:731) ~[patched_1.17.1.jar:git-Paper-378]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-378]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[patched_1.17.1.jar:git-Paper-378]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:831) ~[?:?]

INFO
17:48:05

[AureliumSkills]: Disabling AureliumSkills vBeta 1.2.5
```

### How to reproduce

Put this in config :
![Inkedchrome_p4Xssdhsw5](https://user-images.githubusercontent.com/40535918/141504837-269b91a1-2ba7-4824-8957-41bce09bcf8f.jpg)

With an opened mysql server at the adress and the port

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This means the plugin was unable to connect to the database. Are you sure your database is accessible and is named aureliumskills?
